export interface PredefinedStudent {
  _id?: string;
  id: string;
  name: string;
  email: string;
  nirmaanId: string;
  course: string;
  qualification: string;
  status: "active" | "pending" | "approved";
  avatar: string;
  branch?: string;
  mobile?: string;
}

// Group 1: original Redington Branch students
export const redingtonStudents: PredefinedStudent[] = [
  {
    id: "STU001",
    name: "Abhijit Patra",
    email: "abhijit.patra@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/001",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=AP"
  },
  {
    id: "STU002",
    name: "Ananya Bishoyi",
    email: "ananya.bishoyi@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/002",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=AB"
  },
  {
    id: "STU003",
    name: "Animesh Samantaray",
    email: "animesh.samantaray@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/003",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=AS"
  },
  {
    id: "STU004",
    name: "Ankit Kumar Manjhi",
    email: "ankit.manjhi@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/004",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=AK"
  },
  {
    id: "STU005",
    name: "Ashis Kumar Bhuyan",
    email: "ashis.bhuyan@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/005",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=AKB"
  },
  {
    id: "STU006",
    name: "Asmit Singh",
    email: "asmit.singh@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/006",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=ASI"
  },
  {
    id: "STU007",
    name: "Debasmita Swain",
    email: "debasmita.swain@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/007",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=DS"
  },
  {
    id: "STU008",
    name: "Eleena Jena",
    email: "eleena.jena@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/008",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=EJ"
  },
  {
    id: "STU009",
    name: "Jaychandra Das",
    email: "jaychandra.das@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/009",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=JD"
  },
  {
    id: "STU010",
    name: "Kishor Kumar Sahoo",
    email: "kishor.sahoo@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/010",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=KS"
  },
  {
    id: "STU011",
    name: "Md Salik Ubair",
    email: "salik.ubair@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/011",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=MSU"
  },
  {
    id: "STU012",
    name: "Md Wasiq Anwer",
    email: "wasiq.anwer@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/012",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=MWA"
  },
  {
    id: "STU013",
    name: "Mohammad Hassan",
    email: "mohammad.hassan@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/013",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=MH"
  },
  {
    id: "STU014",
    name: "Mohammad Kashif Iqbal",
    email: "kashif.iqbal@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/014",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=MKI"
  },
  {
    id: "STU015",
    name: "Om Prakash Behura",
    email: "om.behura@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/015",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=OPB"
  },
  {
    id: "STU016",
    name: "Pradeep Kumar Singha",
    email: "pradeep.singha@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/016",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=PKS"
  },
  {
    id: "STU017",
    name: "Prajyakta Patra",
    email: "prajyakta.patra@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/017",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=PP"
  },
  {
    id: "STU018",
    name: "Sai Premananda Das",
    email: "sai.das@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/018",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SPD"
  },
  {
    id: "STU019",
    name: "Shibani Bardhan",
    email: "shibani.bardhan@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/019",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SB"
  },
  {
    id: "STU020",
    name: "Sisir Pradhan",
    email: "sisir.pradhan@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/020",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SP"
  },
  {
    id: "STU021",
    name: "Spandan Kumar Behera",
    email: "spandan.behera@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/021",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SKB"
  },
  {
    id: "STU022",
    name: "Subham Behera",
    email: "subham.behera@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/022",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SBH"
  },
  {
    id: "STU023",
    name: "Subrat Narayan Nanda",
    email: "subrat.nanda@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/023",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SNN"
  },
  {
    id: "STU024",
    name: "Suman Sourav Dash",
    email: "suman.dash@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/024",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SSD"
  },
  {
    id: "STU025",
    name: "Sumit Raj",
    email: "sumit.raj@nirmaan.edu",
    nirmaanId: "REDINGTON/ODISHA/GIFT/025",
    course: "AI/ML",
    qualification: "B.Tech",
    status: "active",
    avatar: "https://via.placeholder.com/150x150/4F46E5/FFFFFF?text=SR"
  }
];

// Group 2: CSE-AI Industry Oriented students
export const industryOrientedStudents: PredefinedStudent[] = [
  {
    id: "2301298291",
    name: "ABHISHEK KUMAR",
    email: "kabhishek2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298291",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AK",
    branch: "Computer Science & Engineering",
    mobile: "7320005612"
  },
  {
    id: "2301298295",
    name: "ABINASH DAS",
    email: "abinashdas2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298295",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AD",
    branch: "Computer Science & Engineering",
    mobile: "9439300910"
  },
  {
    id: "2301298301",
    name: "ADITYA KUSHWAHA",
    email: "akw2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298301",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AK",
    branch: "Computer Science & Engineering",
    mobile: "9835949541"
  },
  {
    id: "2301298308",
    name: "AMARDEEP KUMAR",
    email: "amardeep2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298308",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AK",
    branch: "Computer Science & Engineering",
    mobile: "9931766870"
  },
  {
    id: "2301298314",
    name: "ANIKET RAJ",
    email: "aniketraj2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298314",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AR",
    branch: "Computer Science & Engineering",
    mobile: "6299591861"
  },
  {
    id: "2421298011",
    name: "ANINDITA PANDA",
    email: "anindita2024@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2421298011",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AP",
    branch: "Computer Science & Engineering",
    mobile: "9776808436"
  },
  {
    id: "2301298099",
    name: "ANUSHREE BARIK",
    email: "anushree2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298099",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AB",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "6370903171"
  },
  {
    id: "2301298100",
    name: "ARABINDA SAHOO",
    email: "arabindas2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298100",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AS",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7681024312"
  },
  {
    id: "2301298329",
    name: "ARUN KUMAR PANI",
    email: "apani2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298329",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AP",
    branch: "Computer Science & Engineering",
    mobile: "7077495996"
  },
  {
    id: "2301298109",
    name: "AYUSMAN KAR",
    email: "ayusmank2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298109",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=AK",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "9348338274"
  },
  {
    id: "2301298348",
    name: "BARSHA PRIYADARSHINI LENKA",
    email: "bpl2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298348",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=BL",
    branch: "Computer Science & Engineering",
    mobile: "8093261880"
  },
  {
    id: "2301298117",
    name: "BIKIRAJ BHUYAN",
    email: "bikiraj2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298117",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=BB",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7853890756"
  },
  {
    id: "2301298118",
    name: "BINAYAK DAS",
    email: "binayakd2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298118",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=BD",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7008087770"
  },
  {
    id: "2301298361",
    name: "BISWARANJAN BAGH",
    email: "bbagh2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298361",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=BB",
    branch: "Computer Science & Engineering",
    mobile: "7326906744"
  },
  {
    id: "2301298370",
    name: "CHITTA RANJAN PENTHOI",
    email: "cpenthoi2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298370",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=CP",
    branch: "Computer Science & Engineering",
    mobile: "9078412140"
  },
  {
    id: "2301298380",
    name: "DIBYANJALI SAHU",
    email: "dibyanjali2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298380",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=DS",
    branch: "Computer Science & Engineering",
    mobile: "9668406685"
  },
  {
    id: "2301298390",
    name: "DIVYA PRAKASH KUMAR",
    email: "divyaprakash2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298390",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=DK",
    branch: "Computer Science & Engineering",
    mobile: "7250274439"
  },
  {
    id: "2301298395",
    name: "GYANA RANJAN BARIK",
    email: "grbarik2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298395",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=GB",
    branch: "Computer Science & Engineering",
    mobile: "9938161916"
  },
  {
    id: "2301298399",
    name: "HAREKRISHNA MAHAPATRA",
    email: "harekrishna2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298399",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=HM",
    branch: "Computer Science & Engineering",
    mobile: "9861254100"
  },
  {
    id: "2301298149",
    name: "JYOTI RANJAN JENA",
    email: "jjena2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298149",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=JJ",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "9861357950"
  },
  {
    id: "2301298408",
    name: "JYOTIRMAYEE MALLICK",
    email: "jmallick2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298408",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=JM",
    branch: "Computer Science & Engineering",
    mobile: "8984699542"
  },
  {
    id: "2301298420",
    name: "LAXMIKANTA MALLA",
    email: "laxmikanta2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298420",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=LM",
    branch: "Computer Science & Engineering",
    mobile: "8260658922"
  },
  {
    id: "2301298159",
    name: "LIPSA BARIK",
    email: "lipsa2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298159",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=LB",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "8093524217"
  },
  {
    id: "2301298168",
    name: "MEHTAB ALAM",
    email: "mehtab2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298168",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=MA",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7978269169"
  },
  {
    id: "2301298434",
    name: "MONA KUMARI",
    email: "mona2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298434",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=MK",
    branch: "Computer Science & Engineering",
    mobile: "8651425108"
  },
  {
    id: "2301298438",
    name: "NIKHIL KUSHWAHA",
    email: "nikhilk2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298438",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=NK",
    branch: "Computer Science & Engineering",
    mobile: "7318013639"
  },
  {
    id: "2301298185",
    name: "PRABINA KUMAR KHANDAI",
    email: "prabina2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298185",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=PK",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7681898449"
  },
  {
    id: "2301298452",
    name: "PRAJYOTI PADHI",
    email: "prajyoti2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298452",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=PP",
    branch: "Computer Science & Engineering",
    mobile: "7854059435"
  },
  {
    id: "2301298463",
    name: "PRIYANKA PRIYADARSINEE DAS",
    email: "pdas2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298463",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=PD",
    branch: "Computer Science & Engineering",
    mobile: "7735376878"
  },
  {
    id: "2301298071",
    name: "PUSPANJALI PANDA",
    email: "puspanjali2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298071",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=PP",
    branch: "Computer Engineering",
    mobile: "7205044569"
  },
  {
    id: "2301298476",
    name: "RANI SWAIN",
    email: "raniswain2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298476",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=RS",
    branch: "Computer Science & Engineering",
    mobile: "6372673757"
  },
  {
    id: "2301298494",
    name: "RUPAM BHARGOV",
    email: "rupam2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298494",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=RB",
    branch: "Computer Science & Engineering",
    mobile: "6299678311"
  },
  {
    id: "2301298498",
    name: "SACHIN BEBARTA MOHAPATRA",
    email: "sachinb2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298498",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SM",
    branch: "Computer Science & Engineering",
    mobile: "7327922510"
  },
  {
    id: "2301298207",
    name: "SAFIA FARHAN",
    email: "safia2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298207",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SF",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7205852187"
  },
  {
    id: "2301298211",
    name: "SAMBIT RANJAN DWIBEDI",
    email: "sdwibedi2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298211",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SD",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7847959061"
  },
  {
    id: "2421298021",
    name: "SANDIP DAS",
    email: "sandip2024@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2421298021",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SD",
    branch: "Computer Science & Engineering",
    mobile: "7325802091"
  },
  {
    id: "2301298214",
    name: "SANKALPA SATYADARSHI",
    email: "sankalpa2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298214",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SS",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7978033920"
  },
  {
    id: "2301298515",
    name: "SANTOSH KUMAR SAHOO",
    email: "santoshks2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298515",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SS",
    branch: "Computer Science & Engineering",
    mobile: "8260762910"
  },
  {
    id: "2301298524",
    name: "SATYAJIT SAHOO",
    email: "satyajitsahoo2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298524",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SS",
    branch: "Computer Science & Engineering",
    mobile: "9114373779"
  },
  {
    id: "2301298230",
    name: "SOHAM KUMAR BEHERA",
    email: "skbehera2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298230",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SB",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "9692402855"
  },
  {
    id: "2301298240",
    name: "SRADHANJALI BEHERA",
    email: "sradhanjali2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298240",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SB",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "9437903441"
  },
  {
    id: "2421298023",
    name: "SUBHAM SATAPATHY",
    email: "subham2024@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2421298023",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SS",
    branch: "Computer Science & Engineering",
    mobile: "8637210911"
  },
  {
    id: "2301298577",
    name: "SUMAN KUMAR SAHOO",
    email: "sumansahoo2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298577",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SS",
    branch: "Computer Science & Engineering",
    mobile: "9348071461"
  },
  {
    id: "2301298580",
    name: "SUMIT KUMAR",
    email: "ksumit2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298580",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SK",
    branch: "Computer Science & Engineering",
    mobile: "6299830503"
  },
  {
    id: "2301298267",
    name: "SUNITA NAYAK",
    email: "sunitan2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298267",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SN",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "7077670162"
  },
  {
    id: "2301298585",
    name: "SURYAKANTA MALIK",
    email: "suryakantamalik2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298585",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SM",
    branch: "Computer Science & Engineering",
    mobile: "7846952146"
  },
  {
    _id: "set-e-new-47",
    id: "2301298588",
    name: "SUSHREE MONALISA SAHOO",
    email: "smsahoo2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298588",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SS",
    branch: "Computer Science & Engineering",
    mobile: "7751030200"
  },
  {
    id: "2301298274",
    name: "SWASTI SANTWANA PATI",
    email: "swastipati2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298274",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=SP",
    branch: "Computer Science & Engineering",
    mobile: "7848895308"
  },
  {
    id: "2431298002",
    name: "UMA SANKAR GOUDA",
    email: "uma2024@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2431298002",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=UG",
    branch: "Computer Science & Engineering (Artificial Intelligence)",
    mobile: "8763714089"
  },
  {
    id: "2301298603",
    name: "VIKASH KUMAR SHARMA",
    email: "vsharma2023@gift.edu.in",
    nirmaanId: "GIFT/CSE-AI/2301298603",
    course: "CSE-AI Industry Oriented",
    qualification: "B.Tech",
    status: "approved",
    avatar: "https://via.placeholder.com/150x150/0284C7/FFFFFF?text=VS",
    branch: "Computer Science & Engineering",
    mobile: "9162973970"
  }
];
